import type { Evidence, ActionPlan } from "./types";
import type {
  Approval,
  AIAnalysis,
  ActivityLog,
  DocumentVersion,
  DocumentComment,
} from "./types-extra";

export const seedEvidence: Evidence[] = [
  { id: "ev-001", title: "Antivirus Console — Endpoint Coverage Screenshot", evidence_type: "Screenshot",
    file_url: "/mock/ev-001.png", requirement_id: "req-005", document_id: "doc-004",
    collected_by: "u-004", collection_date: "2026-04-10", retention_period: "2 years",
    expiry_date: "2028-04-10", status: "Valid",
    notes: "Console screenshot shows 1,248/1,250 endpoints protected and updated.", created_at: "2026-04-10T11:00:00Z" },
  { id: "ev-002", title: "Penetration Test Report 2025 — Executive Summary", evidence_type: "Penetration Test Report",
    file_url: "/mock/ev-002.pdf", requirement_id: "req-007", document_id: "doc-006",
    collected_by: "u-008", collection_date: "2025-11-02", retention_period: "5 years",
    expiry_date: "2027-11-02", status: "Valid",
    notes: "Independent specialist report. 3 highs, 7 mediums, 12 lows.", created_at: "2025-11-03T09:00:00Z" },
  { id: "ev-003", title: "Backup Job Log — Production DB (Apr 2026)", evidence_type: "Backup Log",
    file_url: "/mock/ev-003.txt", requirement_id: "req-011", document_id: "doc-009",
    collected_by: "u-004", collection_date: "2026-04-30", retention_period: "1 year",
    expiry_date: "2027-04-30", status: "Valid",
    notes: "Daily full backup successful. Restore drill not yet executed for Q2.", created_at: "2026-04-30T22:00:00Z" },
  { id: "ev-004", title: "Quarterly Vulnerability Scan — Q1 2026", evidence_type: "Security Scan Report",
    file_url: "/mock/ev-004.pdf", requirement_id: "req-006", document_id: "doc-005",
    collected_by: "u-003", collection_date: "2026-03-28", retention_period: "2 years",
    expiry_date: "2028-03-28", status: "Valid",
    notes: "2 criticals open beyond 30-day SLA — see action plan AP-002.", created_at: "2026-03-28T16:00:00Z" },
  { id: "ev-005", title: "Audit Log Sample — Authentication Service (90 days)", evidence_type: "Audit Report",
    file_url: "/mock/ev-005.csv", requirement_id: "req-010", document_id: "doc-008",
    collected_by: "u-004", collection_date: "2026-04-15", retention_period: "5 years",
    expiry_date: "2031-04-15", status: "Valid",
    notes: "Includes IP, user, action, timestamp. Retention configured at 5 years.", created_at: "2026-04-15T08:30:00Z" },
  { id: "ev-006", title: "Incident Drill — Phishing Simulation (Q4 2025)", evidence_type: "Incident Report",
    file_url: "/mock/ev-006.pdf", requirement_id: "req-003", document_id: "doc-003",
    collected_by: "u-003", collection_date: "2025-12-12", retention_period: "2 years",
    expiry_date: "2027-12-12", status: "Pending Update",
    notes: "Old drill. New simulation pending for 2026.", created_at: "2025-12-12T14:00:00Z" },
];

export const seedActionPlans: ActionPlan[] = [
  { id: "ap-001", action_code: "AP-001", requirement_id: "req-003",
    issue_description: "Incident response procedure missing approver signature and current version stamp.",
    corrective_action: "Re-route procedure for sign-off by Ricardo Núñez; update version to 2.2.",
    owner_id: "u-003", priority: "High", risk_level: "Critical", due_date: "2026-06-15",
    status: "In Progress", closure_evidence_id: null,
    reviewer_comments: "Reviewer requested addition of escalation matrix.",
    completed_at: null, created_at: "2026-04-22T10:00:00Z" },
  { id: "ap-002", action_code: "AP-002", requirement_id: "req-006",
    issue_description: "Two critical vulnerabilities open beyond 30-day SLA.",
    corrective_action: "Apply vendor patches in maintenance window 2026-05-18; document compensating controls in interim.",
    owner_id: "u-003", priority: "Critical", risk_level: "Critical", due_date: "2026-05-20",
    status: "Open", closure_evidence_id: null, reviewer_comments: "",
    completed_at: null, created_at: "2026-04-12T11:00:00Z" },
  { id: "ap-003", action_code: "AP-003", requirement_id: "req-009",
    issue_description: "Secure design document does not reference key handling for new mobile module.",
    corrective_action: "Add KMS-backed key lifecycle section; reference cryptographic standard NIST SP 800-57.",
    owner_id: "u-005", priority: "High", risk_level: "High", due_date: "2026-07-30",
    status: "Waiting for Evidence", closure_evidence_id: null, reviewer_comments: "",
    completed_at: null, created_at: "2026-04-25T09:00:00Z" },
  { id: "ap-004", action_code: "AP-004", requirement_id: "req-001",
    issue_description: "Security responsibility document last reviewed 14 months ago.",
    corrective_action: "Re-validate org chart, refresh responsibility matrix, and obtain re-approval.",
    owner_id: "u-003", priority: "Medium", risk_level: "Medium", due_date: "2026-05-10",
    status: "Overdue", closure_evidence_id: null, reviewer_comments: "",
    completed_at: null, created_at: "2026-03-10T10:00:00Z" },
  { id: "ap-005", action_code: "AP-005", requirement_id: "req-011",
    issue_description: "Restore drill not executed for Q2.",
    corrective_action: "Schedule and execute restore drill for production DB by end of May.",
    owner_id: "u-004", priority: "High", risk_level: "High", due_date: "2026-05-30",
    status: "Open", closure_evidence_id: null, reviewer_comments: "",
    completed_at: null, created_at: "2026-04-30T12:00:00Z" },
];
