import type { User } from "./types";

export const seedUsers: User[] = [
  {
    id: "u-001",
    name: "Elena Ramírez",
    email: "elena.ramirez@example.com",
    role: "Admin",
    department: "Compliance",
    status: "Active",
  },
  {
    id: "u-002",
    name: "Marco Villaseñor",
    email: "marco.villasenor@example.com",
    role: "Compliance Manager",
    department: "Compliance",
    status: "Active",
  },
  {
    id: "u-003",
    name: "Sofía Castillo",
    email: "sofia.castillo@example.com",
    role: "IT/Security Owner",
    department: "Information Security",
    status: "Active",
  },
  {
    id: "u-004",
    name: "Daniel Ortega",
    email: "daniel.ortega@example.com",
    role: "IT/Security Owner",
    department: "IT Operations",
    status: "Active",
  },
  {
    id: "u-005",
    name: "Pablo Méndez",
    email: "pablo.mendez@example.com",
    role: "Document Author",
    department: "Engineering",
    status: "Active",
  },
  {
    id: "u-006",
    name: "Laura Iglesias",
    email: "laura.iglesias@example.com",
    role: "Reviewer",
    department: "Internal Audit",
    status: "Active",
  },
  {
    id: "u-007",
    name: "Ricardo Núñez",
    email: "ricardo.nunez@example.com",
    role: "Approver",
    department: "Executive",
    status: "Active",
  },
  {
    id: "u-008",
    name: "Patricia Bravo",
    email: "patricia.bravo@example.com",
    role: "Auditor",
    department: "External Audit",
    status: "Active",
  },
  {
    id: "u-009",
    name: "Andrés Carbajal",
    email: "andres.carbajal@example.com",
    role: "Read-only",
    department: "Risk Management",
    status: "Active",
  },
];
