import type { Requirement } from "./types";

const now = "2026-05-01T09:00:00Z";

function r(
  id: string,
  code: string,
  section: string,
  title: string,
  evaluation_element: string,
  evaluation_criteria: string,
  expected_document_type: string,
  risk_level: Requirement["risk_level"],
  owner_id: string | null,
  reviewer_id: string | null,
  due_date: string,
  status: Requirement["compliance_status"] = "Pending"
): Requirement {
  return {
    id,
    requirement_code: code,
    section,
    title,
    evaluation_element,
    evaluation_criteria,
    expected_document_type,
    compliance_status: status,
    risk_level,
    owner_id,
    reviewer_id,
    due_date,
    methodology: "",
    criteria_for_compliance: "",
    observations: "",
    actions_to_perform: "",
    notes: "",
    human_review_required: false,
    created_at: now,
    updated_at: now,
  };
}

export const seedRequirements: Requirement[] = [
  r("req-001","INF-SEC-001","Security Governance","Responsible Information Security Area",
    "Document identifying the information security responsible area, its head, and responsibilities.",
    "Confirm that roles, responsibilities, and activities of the information security team are defined and approved by a higher authority.",
    "Security responsibility document / organizational role document","High","u-003","u-006","2026-07-15","Partially Compliant"),
  r("req-002","INF-SEC-002","Security Governance","Information Security Policy",
    "Document establishing the institution's information security policy applicable to systems and infrastructure.",
    "Confirm that the policy is approved by senior management and known by involved personnel.",
    "Information security policy","High","u-002","u-006","2026-06-30","Compliant"),
  r("req-003","INC-RESP-001","Incident Response","Security Incident Response Procedure",
    "Document containing measures and actions for handling information security incidents, including communication, follow-up, analysis, documentation, and action plan.",
    "Confirm that incident response procedures are current, signed, versioned, approved, and include responsibilities for each communication stage.",
    "Incident response procedure","Critical","u-003","u-006","2026-06-20","Not Compliant"),
  r("req-004","INC-RESP-002","Incident Response","Incident Reporting to Authority",
    "Procedure to report incidents, anomalies, or threats related to operational infrastructure.",
    "Confirm that reporting times, responsible persons, and communication channels are defined.",
    "Incident reporting procedure","High","u-002","u-006","2026-08-10","Pending"),
  r("req-005","MAL-DET-001","Malware Protection","Real-Time Malware Detection",
    "Documented procedures for using tools that detect viruses and malicious code in real time.",
    "Confirm that malware detection tools are active, updated periodically, and corrective actions are defined.",
    "Antivirus / malware protection procedure","High","u-004","u-006","2026-07-05","Compliant"),
  r("req-006","VULN-MGMT-001","Vulnerability Management","Vulnerability Management Procedure",
    "Policies and procedures for managing vulnerabilities caused by changes, updates, or infrastructure errors.",
    "Confirm that security patch periods, vulnerability scans, mitigation schemes, and resolution timelines are defined.",
    "Vulnerability management policy","Critical","u-003","u-006","2026-05-25","Partially Compliant"),
  r("req-007","PEN-TEST-001","Security Testing","Penetration Testing",
    "Report of the latest penetration test performed by an independent specialist.",
    "Confirm that penetration testing is not older than two years and includes scope, responsible parties, systems tested, and vulnerabilities found.",
    "Penetration testing report","Critical","u-003","u-008","2026-09-30","Under Review"),
  r("req-008","DEV-SEC-001","Secure Software Development","Formal Software Development Process",
    "Document describing the formal software development process including design, development, validation, penetration testing, release, version control, and change tracking.",
    "Confirm that the development process is documented, signed, versioned, and includes required development stages.",
    "Secure SDLC procedure","High","u-005","u-006","2026-07-20","Pending"),
  r("req-009","DEV-SEC-002","Secure Software Development","Secure Design and Implementation Controls",
    "Document proving that authentication, encryption, electronic signatures, integrity, non-repudiation, and secure key handling are considered during design and implementation.",
    "Confirm that security mechanisms are implemented, validated, tested, and active in production.",
    "Secure design document / security validation report","Critical","u-005","u-006","2026-08-15","Not Compliant"),
  r("req-010","LOG-RET-001","Logging and Monitoring","Audit Log Retention",
    "Procedures and evidence showing access and activity logs are stored for the required retention period.",
    "Confirm that logs contain IP address, credentials/user identity, user activities, and are retained for at least the required period.",
    "Logging and monitoring procedure","High","u-004","u-006","2026-06-10","Compliant"),
  r("req-011","BACKUP-001","Backup and Continuity","Backup Procedure",
    "Documented backup procedures and evidence of backup execution.",
    "Confirm that backup policies, backup frequency, responsible users, retention period, and restoration process are defined.",
    "Backup procedure and backup logs","High","u-004","u-006","2026-07-01","Partially Compliant"),
  r("req-012","BCP-001","Business Continuity","Business Continuity Procedures",
    "Documented procedures for business continuity and operational recovery.",
    "Confirm that continuity procedures are documented, tested, reviewed, and linked to responsible teams.",
    "Business continuity plan","High","u-002","u-008","2026-10-15","Pending"),
];
